# Generated by Django 2.2.3 on 2019-08-02 17:08

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='featured',
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='get_featured_image_path')),
                ('slug', models.SlugField(unique=True)),
                ('review', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Language')),
            ],
        ),
    ]
