# Generated by Django 2.2.3 on 2019-08-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190802_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='featured_vid',
            field=models.FileField(blank=True, null=True, upload_to='get_vid'),
        ),
    ]
