# Generated by Django 2.2.3 on 2019-08-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190802_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
