# Generated by Django 2.2.3 on 2019-08-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190802_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='summary_question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
