# Generated by Django 2.2.3 on 2019-08-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_content_summary_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to='get_image_path_note'),
        ),
    ]
