# Generated by Django 2.2.3 on 2019-08-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_content_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='note_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
