# Generated by Django 2.2.3 on 2019-08-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190802_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paper_work',
            field=models.URLField(blank=True, null=True),
        ),
    ]
