# Generated by Django 2.2.3 on 2019-08-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190802_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
