# Generated by Django 2.2.3 on 2019-08-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_projectidea_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
